#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["CronJob.Template/CronJob.Template.csproj", "CronJob.Template/"]
RUN dotnet restore "CronJob.Template/CronJob.Template.csproj"
COPY . .
WORKDIR "/src/CronJob.Template"
RUN dotnet build "CronJob.Template.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CronJob.Template.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CronJob.Template.dll"]
